/**
 * mockData.js
 * -----------
 * Fallback events used when GDELT is unreachable.
 * Schema matches the normalized GDELT output from gdeltFetcher.js.
 *
 * Fields:
 *   event_id_cnty  - Unique string ID
 *   event_date     - YYYY-MM-DD
 *   event_type     - Sentinel classification
 *   sub_event_type - Human-readable CAMEO description
 *   actor1, actor2
 *   country, admin1, location
 *   latitude, longitude
 *   impact_score   - 0–10 conflict severity (inverted Goldstein)
 *   goldstein_scale
 *   num_mentions, num_sources, num_articles
 *   avg_tone
 *   source_url
 *   notes
 */

export const mockEvents = [
  {
    event_id_cnty: 'MOCK-001',
    event_date: '2026-04-07',
    event_type: 'Battles',
    sub_event_type: 'Fight with small arms',
    actor1: 'Military Forces of Ukraine',
    actor2: 'Military Forces of Russia',
    country: 'Ukraine',
    admin1: 'Donetsk',
    location: 'Avdiivka, Donetsk, Ukraine',
    latitude: 48.1357,
    longitude: 37.7533,
    impact_score: 8,
    goldstein_scale: -8.0,
    num_mentions: 142,
    num_sources: 38,
    num_articles: 89,
    avg_tone: -6.4,
    source_url: 'https://www.reuters.com',
    notes: 'Fight with small arms — Military Forces of Ukraine vs. Military Forces of Russia in Avdiivka, Donetsk, Ukraine. Reported across 142 mention(s) from 38 outlets. Goldstein: -8.0.',
  },
  {
    event_id_cnty: 'MOCK-002',
    event_date: '2026-04-07',
    event_type: 'Explosions/Remote violence',
    sub_event_type: 'Conduct airstrike',
    actor1: 'Military Forces of Israel',
    actor2: 'Hamas',
    country: 'Gaza Strip',
    admin1: 'Gaza',
    location: 'Gaza City, Gaza Strip',
    latitude: 31.5017,
    longitude: 34.4668,
    impact_score: 9,
    goldstein_scale: -9.0,
    num_mentions: 310,
    num_sources: 74,
    num_articles: 201,
    avg_tone: -8.2,
    source_url: 'https://www.bbc.com',
    notes: 'Conduct airstrike — Military Forces of Israel vs. Hamas in Gaza City, Gaza Strip. Reported across 310 mention(s) from 74 outlets. Goldstein: -9.0.',
  },
  {
    event_id_cnty: 'MOCK-003',
    event_date: '2026-04-06',
    event_type: 'Violence against civilians',
    sub_event_type: 'Conduct bombing',
    actor1: 'Al-Shabaab',
    actor2: 'Civilians',
    country: 'Somalia',
    admin1: 'Banaadir',
    location: 'Mogadishu, Banaadir, Somalia',
    latitude: 2.0469,
    longitude: 45.3182,
    impact_score: 9,
    goldstein_scale: -9.5,
    num_mentions: 88,
    num_sources: 21,
    num_articles: 52,
    avg_tone: -7.1,
    source_url: 'https://www.aljazeera.com',
    notes: 'Conduct bombing — Al-Shabaab vs. Civilians in Mogadishu, Banaadir, Somalia. Reported across 88 mention(s) from 21 outlets. Goldstein: -9.5.',
  },
  {
    event_id_cnty: 'MOCK-004',
    event_date: '2026-04-07',
    event_type: 'Protests',
    sub_event_type: 'Demonstrate or rally',
    actor1: 'Opposition Group',
    actor2: 'Government of Venezuela',
    country: 'Venezuela',
    admin1: 'Distrito Capital',
    location: 'Caracas, Venezuela',
    latitude: 10.4806,
    longitude: -66.9036,
    impact_score: 3,
    goldstein_scale: -3.4,
    num_mentions: 45,
    num_sources: 14,
    num_articles: 30,
    avg_tone: -3.2,
    source_url: 'https://www.apnews.com',
    notes: 'Demonstrate or rally — Opposition Group vs. Government of Venezuela in Caracas, Venezuela. Reported across 45 mention(s) from 14 outlets. Goldstein: -3.4.',
  },
  {
    event_id_cnty: 'MOCK-005',
    event_date: '2026-04-06',
    event_type: 'Battles',
    sub_event_type: 'Employ air, naval, or artillery force',
    actor1: 'Houthi Forces',
    actor2: 'Military Forces of Saudi Arabia',
    country: 'Yemen',
    admin1: 'Saada',
    location: 'Saada, Yemen',
    latitude: 16.9346,
    longitude: 43.7632,
    impact_score: 8,
    goldstein_scale: -8.0,
    num_mentions: 97,
    num_sources: 29,
    num_articles: 61,
    avg_tone: -5.9,
    source_url: 'https://www.reuters.com',
    notes: 'Employ air, naval, or artillery force — Houthi Forces vs. Military Forces of Saudi Arabia in Saada, Yemen. Reported across 97 mention(s) from 29 outlets. Goldstein: -8.0.',
  },
  {
    event_id_cnty: 'MOCK-006',
    event_date: '2026-04-05',
    event_type: 'Strategic developments',
    sub_event_type: 'Mobilize or increase armed forces',
    actor1: 'Military Forces of China',
    actor2: 'Military Forces of Taiwan',
    country: 'Taiwan',
    admin1: 'Taipei',
    location: 'Taipei, Taiwan',
    latitude: 25.0330,
    longitude: 121.5654,
    impact_score: 5,
    goldstein_scale: -5.0,
    num_mentions: 213,
    num_sources: 56,
    num_articles: 147,
    avg_tone: -4.8,
    source_url: 'https://www.bbc.com',
    notes: 'Mobilize or increase armed forces — Military Forces of China vs. Military Forces of Taiwan in Taipei, Taiwan. Reported across 213 mention(s) from 56 outlets. Goldstein: -5.0.',
  },
  {
    event_id_cnty: 'MOCK-007',
    event_date: '2026-04-06',
    event_type: 'Violence against civilians',
    sub_event_type: 'Abduct, hijack, or take hostage',
    actor1: 'Boko Haram',
    actor2: 'Civilians',
    country: 'Nigeria',
    admin1: 'Borno',
    location: 'Maiduguri, Borno, Nigeria',
    latitude: 11.8311,
    longitude: 13.1510,
    impact_score: 9,
    goldstein_scale: -9.0,
    num_mentions: 53,
    num_sources: 15,
    num_articles: 34,
    avg_tone: -6.7,
    source_url: 'https://www.aljazeera.com',
    notes: 'Abduct, hijack, or take hostage — Boko Haram vs. Civilians in Maiduguri, Borno, Nigeria. Reported across 53 mention(s) from 15 outlets. Goldstein: -9.0.',
  },
  {
    event_id_cnty: 'MOCK-008',
    event_date: '2026-04-07',
    event_type: 'Riots',
    sub_event_type: 'Protest violently, riot',
    actor1: 'Protesters',
    actor2: 'Police Forces of Sudan',
    country: 'Sudan',
    admin1: 'Khartoum',
    location: 'Khartoum, Sudan',
    latitude: 15.5007,
    longitude: 32.5599,
    impact_score: 6,
    goldstein_scale: -6.0,
    num_mentions: 71,
    num_sources: 19,
    num_articles: 45,
    avg_tone: -5.2,
    source_url: 'https://www.apnews.com',
    notes: 'Protest violently, riot — Protesters vs. Police Forces of Sudan in Khartoum, Sudan. Reported across 71 mention(s) from 19 outlets. Goldstein: -6.0.',
  },
  {
    event_id_cnty: 'MOCK-009',
    event_date: '2026-04-05',
    event_type: 'Battles',
    sub_event_type: 'Fight',
    actor1: 'Junta Forces Myanmar',
    actor2: 'Kachin Independence Army',
    country: 'Myanmar',
    admin1: 'Kachin',
    location: 'Myitkyina, Kachin, Myanmar',
    latitude: 25.3824,
    longitude: 97.3958,
    impact_score: 8,
    goldstein_scale: -8.0,
    num_mentions: 62,
    num_sources: 17,
    num_articles: 39,
    avg_tone: -6.1,
    source_url: 'https://www.reuters.com',
    notes: 'Fight — Junta Forces Myanmar vs. Kachin Independence Army in Myitkyina, Kachin, Myanmar. Reported across 62 mention(s) from 17 outlets. Goldstein: -8.0.',
  },
  {
    event_id_cnty: 'MOCK-010',
    event_date: '2026-04-04',
    event_type: 'Explosions/Remote violence',
    sub_event_type: 'Conduct IED / roadside bombing',
    actor1: 'Taliban',
    actor2: 'Military Forces of Afghanistan',
    country: 'Afghanistan',
    admin1: 'Kabul',
    location: 'Kabul, Afghanistan',
    latitude: 34.5553,
    longitude: 69.2075,
    impact_score: 9,
    goldstein_scale: -9.0,
    num_mentions: 119,
    num_sources: 33,
    num_articles: 76,
    avg_tone: -7.4,
    source_url: 'https://www.bbc.com',
    notes: 'Conduct IED / roadside bombing — Taliban vs. Military Forces of Afghanistan in Kabul, Afghanistan. Reported across 119 mention(s) from 33 outlets. Goldstein: -9.0.',
  },
  {
    event_id_cnty: 'MOCK-011',
    event_date: '2026-04-06',
    event_type: 'Battles',
    sub_event_type: 'Fight with small arms',
    actor1: 'Rapid Support Forces',
    actor2: 'Sudanese Armed Forces',
    country: 'Sudan',
    admin1: 'Darfur',
    location: 'El Fasher, Darfur, Sudan',
    latitude: 13.6289,
    longitude: 25.3496,
    impact_score: 8,
    goldstein_scale: -8.0,
    num_mentions: 103,
    num_sources: 27,
    num_articles: 66,
    avg_tone: -6.8,
    source_url: 'https://www.aljazeera.com',
    notes: 'Fight with small arms — Rapid Support Forces vs. Sudanese Armed Forces in El Fasher, Darfur, Sudan. Reported across 103 mention(s) from 27 outlets. Goldstein: -8.0.',
  },
  {
    event_id_cnty: 'MOCK-012',
    event_date: '2026-04-05',
    event_type: 'Strategic developments',
    sub_event_type: 'Threaten with military force',
    actor1: 'Government of North Korea',
    actor2: 'Government of United States',
    country: 'North Korea',
    admin1: 'Pyongyang',
    location: 'Pyongyang, North Korea',
    latitude: 39.0392,
    longitude: 125.7625,
    impact_score: 5,
    goldstein_scale: -5.0,
    num_mentions: 188,
    num_sources: 51,
    num_articles: 122,
    avg_tone: -4.3,
    source_url: 'https://www.reuters.com',
    notes: 'Threaten with military force — Government of North Korea vs. Government of United States in Pyongyang, North Korea. Reported across 188 mention(s) from 51 outlets. Goldstein: -5.0.',
  },
  {
    event_id_cnty: 'MOCK-013',
    event_date: '2026-04-07',
    event_type: 'Violence against civilians',
    sub_event_type: 'Engage in mass killings',
    actor1: 'Wagner Group',
    actor2: 'Civilians',
    country: 'Mali',
    admin1: 'Mopti',
    location: 'Mopti, Mali',
    latitude: 14.4843,
    longitude: -4.1977,
    impact_score: 10,
    goldstein_scale: -10.0,
    num_mentions: 76,
    num_sources: 22,
    num_articles: 48,
    avg_tone: -8.6,
    source_url: 'https://www.apnews.com',
    notes: 'Engage in mass killings — Wagner Group vs. Civilians in Mopti, Mali. Reported across 76 mention(s) from 22 outlets. Goldstein: -10.0.',
  },
  {
    event_id_cnty: 'MOCK-014',
    event_date: '2026-04-04',
    event_type: 'Protests',
    sub_event_type: 'Demonstrate or rally',
    actor1: 'Students',
    actor2: 'Government of Bangladesh',
    country: 'Bangladesh',
    admin1: 'Dhaka',
    location: 'Dhaka, Bangladesh',
    latitude: 23.8103,
    longitude: 90.4125,
    impact_score: 3,
    goldstein_scale: -3.4,
    num_mentions: 38,
    num_sources: 12,
    num_articles: 24,
    avg_tone: -2.9,
    source_url: 'https://www.bbc.com',
    notes: 'Demonstrate or rally — Students vs. Government of Bangladesh in Dhaka, Bangladesh. Reported across 38 mention(s) from 12 outlets. Goldstein: -3.4.',
  },
  {
    event_id_cnty: 'MOCK-015',
    event_date: '2026-04-03',
    event_type: 'Explosions/Remote violence',
    sub_event_type: 'Conduct artillery / rocket strike',
    actor1: 'Military Forces of Russia',
    actor2: 'Civilians',
    country: 'Ukraine',
    admin1: 'Kharkiv',
    location: 'Kharkiv, Ukraine',
    latitude: 49.9935,
    longitude: 36.2304,
    impact_score: 9,
    goldstein_scale: -9.0,
    num_mentions: 167,
    num_sources: 44,
    num_articles: 108,
    avg_tone: -7.8,
    source_url: 'https://www.reuters.com',
    notes: 'Conduct artillery / rocket strike — Military Forces of Russia vs. Civilians in Kharkiv, Ukraine. Reported across 167 mention(s) from 44 outlets. Goldstein: -9.0.',
  },
  {
    event_id_cnty: 'MOCK-016',
    event_date: '2026-04-06',
    event_type: 'Battles',
    sub_event_type: 'Fight',
    actor1: 'JNIM',
    actor2: 'Military Forces of Burkina Faso',
    country: 'Burkina Faso',
    admin1: 'Sahel',
    location: 'Dori, Sahel, Burkina Faso',
    latitude: 14.0358,
    longitude: -0.0335,
    impact_score: 7,
    goldstein_scale: -7.5,
    num_mentions: 44,
    num_sources: 13,
    num_articles: 28,
    avg_tone: -5.7,
    source_url: 'https://www.aljazeera.com',
    notes: 'Fight — JNIM vs. Military Forces of Burkina Faso in Dori, Sahel, Burkina Faso. Reported across 44 mention(s) from 13 outlets. Goldstein: -7.5.',
  },
  {
    event_id_cnty: 'MOCK-017',
    event_date: '2026-04-05',
    event_type: 'Strategic developments',
    sub_event_type: 'Increase military alert status',
    actor1: 'Military Forces of Iran',
    actor2: 'Military Forces of Israel',
    country: 'Iran',
    admin1: 'Tehran',
    location: 'Tehran, Iran',
    latitude: 35.6892,
    longitude: 51.3890,
    impact_score: 5,
    goldstein_scale: -5.0,
    num_mentions: 256,
    num_sources: 66,
    num_articles: 173,
    avg_tone: -5.1,
    source_url: 'https://www.bbc.com',
    notes: 'Increase military alert status — Military Forces of Iran vs. Military Forces of Israel in Tehran, Iran. Reported across 256 mention(s) from 66 outlets. Goldstein: -5.0.',
  },
  {
    event_id_cnty: 'MOCK-018',
    event_date: '2026-04-07',
    event_type: 'Violence against civilians',
    sub_event_type: 'Physically assault',
    actor1: 'FARC Dissident Groups',
    actor2: 'Civilians',
    country: 'Colombia',
    admin1: 'Cauca',
    location: 'Popayan, Cauca, Colombia',
    latitude: 2.4448,
    longitude: -76.6147,
    impact_score: 7,
    goldstein_scale: -7.0,
    num_mentions: 31,
    num_sources: 9,
    num_articles: 19,
    avg_tone: -5.4,
    source_url: 'https://www.apnews.com',
    notes: 'Physically assault — FARC Dissident Groups vs. Civilians in Popayan, Cauca, Colombia. Reported across 31 mention(s) from 9 outlets. Goldstein: -7.0.',
  },
  {
    event_id_cnty: 'MOCK-019',
    event_date: '2026-04-04',
    event_type: 'Explosions/Remote violence',
    sub_event_type: 'Conduct suicide bombing',
    actor1: 'Islamic State Iraq and Syria',
    actor2: 'Civilians',
    country: 'Iraq',
    admin1: 'Baghdad',
    location: 'Baghdad, Iraq',
    latitude: 33.3152,
    longitude: 44.3661,
    impact_score: 9,
    goldstein_scale: -9.0,
    num_mentions: 134,
    num_sources: 37,
    num_articles: 88,
    avg_tone: -7.9,
    source_url: 'https://www.reuters.com',
    notes: 'Conduct suicide bombing — Islamic State Iraq and Syria vs. Civilians in Baghdad, Iraq. Reported across 134 mention(s) from 37 outlets. Goldstein: -9.0.',
  },
  {
    event_id_cnty: 'MOCK-020',
    event_date: '2026-04-03',
    event_type: 'Riots',
    sub_event_type: 'Protest violently, riot',
    actor1: 'Protesters',
    actor2: 'Police Forces of Ethiopia',
    country: 'Ethiopia',
    admin1: 'Oromia',
    location: 'Addis Ababa, Ethiopia',
    latitude: 9.0250,
    longitude: 38.7469,
    impact_score: 6,
    goldstein_scale: -6.0,
    num_mentions: 59,
    num_sources: 16,
    num_articles: 37,
    avg_tone: -4.9,
    source_url: 'https://www.bbc.com',
    notes: 'Protest violently, riot — Protesters vs. Police Forces of Ethiopia in Addis Ababa, Ethiopia. Reported across 59 mention(s) from 16 outlets. Goldstein: -6.0.',
  },
  {
    event_id_cnty: 'MOCK-021',
    event_date: '2026-04-06',
    event_type: 'Battles',
    sub_event_type: 'Conduct airstrike',
    actor1: 'Military Forces of Syria',
    actor2: 'Rebel Groups',
    country: 'Syria',
    admin1: 'Idlib',
    location: 'Idlib, Syria',
    latitude: 35.9306,
    longitude: 36.6339,
    impact_score: 8,
    goldstein_scale: -8.0,
    num_mentions: 84,
    num_sources: 23,
    num_articles: 53,
    avg_tone: -6.5,
    source_url: 'https://www.aljazeera.com',
    notes: 'Conduct airstrike — Military Forces of Syria vs. Rebel Groups in Idlib, Syria. Reported across 84 mention(s) from 23 outlets. Goldstein: -8.0.',
  },
  {
    event_id_cnty: 'MOCK-022',
    event_date: '2026-04-02',
    event_type: 'Strategic developments',
    sub_event_type: 'Impose blockade, restrict movement',
    actor1: 'Military Forces of Russia',
    actor2: 'Government of Ukraine',
    country: 'Ukraine',
    admin1: 'Odessa',
    location: 'Odessa, Ukraine',
    latitude: 46.4825,
    longitude: 30.7233,
    impact_score: 6,
    goldstein_scale: -6.0,
    num_mentions: 112,
    num_sources: 31,
    num_articles: 72,
    avg_tone: -4.6,
    source_url: 'https://www.reuters.com',
    notes: 'Impose blockade, restrict movement — Military Forces of Russia vs. Government of Ukraine in Odessa, Ukraine. Reported across 112 mention(s) from 31 outlets. Goldstein: -6.0.',
  },
  {
    event_id_cnty: 'MOCK-023',
    event_date: '2026-04-05',
    event_type: 'Violence against civilians',
    sub_event_type: 'Engage in mass expulsion',
    actor1: 'Arakan Army',
    actor2: 'Civilians',
    country: 'Myanmar',
    admin1: 'Rakhine',
    location: 'Sittwe, Rakhine, Myanmar',
    latitude: 20.1464,
    longitude: 92.8977,
    impact_score: 8,
    goldstein_scale: -8.5,
    num_mentions: 67,
    num_sources: 18,
    num_articles: 41,
    avg_tone: -7.2,
    source_url: 'https://www.apnews.com',
    notes: 'Engage in mass expulsion — Arakan Army vs. Civilians in Sittwe, Rakhine, Myanmar. Reported across 67 mention(s) from 18 outlets. Goldstein: -8.5.',
  },
  {
    event_id_cnty: 'MOCK-024',
    event_date: '2026-04-07',
    event_type: 'Protests',
    sub_event_type: 'Conduct strike or boycott',
    actor1: 'Labor Unions',
    actor2: 'Government of France',
    country: 'France',
    admin1: 'Ile-de-France',
    location: 'Paris, France',
    latitude: 48.8566,
    longitude: 2.3522,
    impact_score: 2,
    goldstein_scale: -2.0,
    num_mentions: 89,
    num_sources: 25,
    num_articles: 57,
    avg_tone: -2.1,
    source_url: 'https://www.bbc.com',
    notes: 'Conduct strike or boycott — Labor Unions vs. Government of France in Paris, France. Reported across 89 mention(s) from 25 outlets. Goldstein: -2.0.',
  },
  {
    event_id_cnty: 'MOCK-025',
    event_date: '2026-04-04',
    event_type: 'Battles',
    sub_event_type: 'Fight',
    actor1: 'ISWAP',
    actor2: 'Nigerian Army',
    country: 'Nigeria',
    admin1: 'Borno',
    location: 'Baga, Borno, Nigeria',
    latitude: 13.6248,
    longitude: 14.6018,
    impact_score: 8,
    goldstein_scale: -8.0,
    num_mentions: 48,
    num_sources: 14,
    num_articles: 30,
    avg_tone: -6.3,
    source_url: 'https://www.aljazeera.com',
    notes: 'Fight — ISWAP vs. Nigerian Army in Baga, Borno, Nigeria. Reported across 48 mention(s) from 14 outlets. Goldstein: -8.0.',
  },
];
